// src/components/common/Icons/index.js
export { FaUserGraduate, FaBook, FaChalkboardTeacher } from 'react-icons/fa';
export { FiLogOut } from 'react-icons/fi';
// src/components/common/Icons/index.js
// Material UI Icons
export {
  Home as HomeIcon,
  School as SchoolIcon,
  Person as PersonIcon,
  Settings as SettingsIcon,
  Dashboard as DashboardIcon,
  Book as BookIcon,
  VideoCall as VideoCallIcon,
  Chat as ChatIcon,
  Assignment as AssignmentIcon,
  Assessment as AssessmentIcon,
  Upload as UploadIcon,
  Download as DownloadIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Remove as RemoveIcon,
  Close as CloseIcon,
  Menu as MenuIcon,
  Search as SearchIcon,
  Notifications as NotificationsIcon,
  AccountCircle as AccountCircleIcon,
  ExitToApp as LogoutIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Email as EmailIcon,
  Lock as LockIcon,
  Phone as PhoneIcon,
  CheckCircle as CheckCircleIcon,
  Error as ErrorIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  ArrowBack as ArrowBackIcon,
  ArrowForward as ArrowForwardIcon,
  KeyboardArrowDown as ArrowDownIcon,
  KeyboardArrowUp as ArrowUpIcon,
  PlayArrow as PlayIcon,
  Pause as PauseIcon,
  Stop as StopIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  Videocam as VideocamIcon,
  VideocamOff as VideocamOffIcon,
  ScreenShare as ScreenShareIcon,
  StopScreenShare as StopScreenShareIcon,
  Send as SendIcon,
  AttachFile as AttachFileIcon,
  EmojiEmotions as EmojiIcon,
  MoreVert as MoreVertIcon,
  Fullscreen as FullscreenIcon,
  FullscreenExit as FullscreenExitIcon,
  Grade as GradeIcon,
  Star as StarIcon,
  StarBorder as StarBorderIcon,
  Favorite as FavoriteIcon,
  FavoriteBorder as FavoriteBorderIcon,
  Schedule as ScheduleIcon,
  CalendarToday as CalendarIcon,
  AccessTime as TimeIcon,
  LocationOn as LocationIcon,
  Language as LanguageIcon,
  Brightness4 as DarkModeIcon,
  Brightness7 as LightModeIcon,
  Group as GroupIcon,
  PersonAdd as PersonAddIcon,
  SupervisorAccount as SupervisorIcon,
  EmojiEvents as TrophyIcon,
  TrendingUp as TrendingUpIcon,
  BarChart as BarChartIcon,
  PieChart as PieChartIcon,
  Timeline as TimelineIcon,
  FilterList as FilterIcon,
  Sort as SortIcon,
  Refresh as RefreshIcon,
  CloudUpload as CloudUploadIcon,
  CloudDownload as CloudDownloadIcon,
  Folder as FolderIcon,
  InsertDriveFile as FileIcon,
  Image as ImageIcon,
  PictureAsPdf as PdfIcon,
  Description as DocumentIcon,
  Link as LinkIcon,
  Share as ShareIcon,
  ContentCopy as CopyIcon,
  Print as PrintIcon,
  Save as SaveIcon,
  Cancel as CancelIcon,
  Done as DoneIcon,
  DoneAll as DoneAllIcon,
  Pending as PendingIcon,
  HourglassEmpty as HourglassIcon,
  Quiz as QuizIcon,
  LiveTv as LiveIcon,
  OndemandVideo as VideoIcon,
  Headset as HeadsetIcon,
  SupportAgent as SupportIcon,
  Help as HelpIcon,
  Feedback as FeedbackIcon,
  ReportProblem as ReportIcon,
  Security as SecurityIcon,
  VpnKey as KeyIcon,
  Badge as BadgeIcon,
  WorkspacePremium as PremiumIcon,
  LocalFireDepartment as FireIcon,
  AutoAwesome as SparkleIcon,
  Rocket as RocketIcon,
  Psychology as BrainIcon,
  Lightbulb as LightbulbIcon,
  MenuBook as MenuBookIcon,
  Class as ClassIcon,
  Category as CategoryIcon,
  Label as LabelIcon,
  LocalOffer as TagIcon,
  Payment as PaymentIcon,
  CreditCard as CreditCardIcon,
  Receipt as ReceiptIcon,
  ShoppingCart as CartIcon,
  Facebook as FacebookIcon,
  Twitter as TwitterIcon,
  Instagram as InstagramIcon,
  LinkedIn as LinkedInIcon,
  YouTube as YouTubeIcon,
  GitHub as GitHubIcon,
  Apple as AppleIcon,
  Android as AndroidIcon,
  Computer as ComputerIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Speed as SpeedIcon,
  Tune as TuneIcon,
  Palette as PaletteIcon,
  FormatSize as TextSizeIcon,
  FormatBold as BoldIcon,
  FormatItalic as ItalicIcon,
  FormatUnderlined as UnderlineIcon,
  FormatListBulleted as BulletListIcon,
  FormatListNumbered as NumberListIcon,
  Code as CodeIcon,
  DataObject as DataIcon,
  Terminal as TerminalIcon,
  BugReport as BugIcon,
  Build as BuildIcon,
  Extension as ExtensionIcon,
  Widgets as WidgetsIcon,
  ViewModule as GridViewIcon,
  ViewList as ListViewIcon,
  ViewAgenda as AgendaViewIcon,
  Map as MapIcon,
  Public as GlobeIcon,
  Translate as TranslateIcon,
  RecordVoiceOver as VoiceIcon,
  Subtitles as SubtitlesIcon,
  ClosedCaption as CaptionIcon,
  VolumeUp as VolumeUpIcon,
  VolumeDown as VolumeDownIcon,
  VolumeMute as VolumeMuteIcon,
  VolumeOff as VolumeOffIcon,
  SkipPrevious as SkipPrevIcon,
  SkipNext as SkipNextIcon,
  Replay as ReplayIcon,
  Forward10 as Forward10Icon,
  Replay10 as Replay10Icon,
  Speed as PlaybackSpeedIcon,
  HighQuality as QualityIcon,
  Hd as HdIcon,
  FourK as FourKIcon,
  Cast as CastIcon,
  AirPlay as AirPlayIcon,
  PictureInPicture as PipIcon,
  Crop as CropIcon,
  RotateLeft as RotateLeftIcon,
  RotateRight as RotateRightIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  CenterFocusStrong as FocusIcon,
  Flip as FlipIcon,
  FilterNone as FilterNoneIcon,
  Layers as LayersIcon,
  GridOn as GridIcon,
  BorderAll as BorderIcon,
  Straighten as RulerIcon,
  Gesture as DrawIcon,
  Brush as BrushIcon,
  ColorLens as ColorIcon,
  TextFields as TextFieldsIcon,
  Title as TitleIcon,
  FormatQuote as QuoteIcon,
  InsertLink as InsertLinkIcon,
  AddPhotoAlternate as AddPhotoIcon,
  MovieCreation as MovieIcon,
  AudioFile as AudioIcon,
  Attachment as AttachmentIcon,
  CloudQueue as CloudIcon,
  CloudDone as CloudDoneIcon,
  CloudOff as CloudOffIcon,
  Sync as SyncIcon,
  SyncDisabled as SyncDisabledIcon,
  SyncProblem as SyncProblemIcon,
  Cached as CachedIcon,
  Autorenew as AutorenewIcon,
  Loop as LoopIcon,
  Shuffle as ShuffleIcon,
  RepeatOne as RepeatOneIcon,
  Repeat as RepeatIcon,
  QueueMusic as QueueIcon,
  PlaylistAdd as PlaylistAddIcon,
  PlaylistPlay as PlaylistPlayIcon,
  LibraryMusic as LibraryMusicIcon,
  LibraryBooks as LibraryBooksIcon,
  LocalLibrary as LocalLibraryIcon,
  CollectionsBookmark as CollectionsIcon,
  Bookmark as BookmarkIcon,
  BookmarkBorder as BookmarkBorderIcon,
  Bookmarks as BookmarksIcon,
  Archive as ArchiveIcon,
  Unarchive as UnarchiveIcon,
  Inventory as InventoryIcon,
  Inbox as InboxIcon,
  Outbox as OutboxIcon,
  Drafts as DraftsIcon,
  MarkunreadMailbox as MailboxIcon,
  MarkEmailRead as EmailReadIcon,
  MarkEmailUnread as EmailUnreadIcon,
  ForwardToInbox as ForwardEmailIcon,
  ReplyAll as ReplyAllIcon,
  Reply as ReplyIcon,
  Forward as ForwardIcon,
  Undo as UndoIcon,
  Redo as RedoIcon,
  History as HistoryIcon,
  Update as UpdateIcon,
  Restore as RestoreIcon,
  RestoreFromTrash as RestoreTrashIcon,
  DeleteForever as DeleteForeverIcon,
  DeleteSweep as DeleteSweepIcon,
  RemoveCircle as RemoveCircleIcon,
  AddCircle as AddCircleIcon,
  RemoveCircleOutline as RemoveCircleOutlineIcon,
  AddCircleOutline as AddCircleOutlineIcon,
  Expand as ExpandIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  FirstPage as FirstPageIcon,
  LastPage as LastPageIcon,
  NavigateBefore as NavBeforeIcon,
  NavigateNext as NavNextIcon,
  DoubleArrow as DoubleArrowIcon,
  SwapHoriz as SwapHorizIcon,
  SwapVert as SwapVertIcon,
  CompareArrows as CompareIcon,
  UnfoldMore as UnfoldMoreIcon,
  UnfoldLess as UnfoldLessIcon,
  OpenInNew as OpenNewIcon,
  OpenInFull as OpenFullIcon,
  CloseFullscreen as CloseFullscreenIcon,
  Minimize as MinimizeIcon,
  Maximize as MaximizeIcon,
  AspectRatio as AspectRatioIcon,
  FitScreen as FitScreenIcon,
  CropFree as CropFreeIcon,
  ViewInAr as View3DIcon,
  ThreeDRotation as Rotate3DIcon,
  FlipToFront as BringFrontIcon,
  FlipToBack as SendBackIcon,
  SelectAll as SelectAllIcon,
  Deselect as DeselectIcon,
  CheckBox as CheckBoxIcon,
  CheckBoxOutlineBlank as CheckBoxBlankIcon,
  IndeterminateCheckBox as CheckBoxIndeterminateIcon,
  RadioButtonChecked as RadioCheckedIcon,
  RadioButtonUnchecked as RadioUncheckedIcon,
  ToggleOn as ToggleOnIcon,
  ToggleOff as ToggleOffIcon,
  PushPin as PinIcon,
  Flag as FlagIcon,
  OutlinedFlag as FlagOutlineIcon,
  Tour as TourIcon,
  Explore as ExploreIcon,
  NearMe as NearMeIcon,
  Navigation as NavigationIcon,
  MyLocation as MyLocationIcon,
  GpsFixed as GpsIcon,
  Compass as CompassIcon,
  DirectionsRun as RunIcon,
  DirectionsWalk as WalkIcon,
  DirectionsBike as BikeIcon,
  DirectionsCar as CarIcon,
  DirectionsBus as BusIcon,
  DirectionsTransit as TransitIcon,
  Flight as FlightIcon,
  DirectionsBoat as BoatIcon,
  Train as TrainIcon,
  Subway as SubwayIcon,
  LocalTaxi as TaxiIcon,
  LocalShipping as ShippingIcon,
  LocalMall as MallIcon,
  Store as StoreIcon,
  Storefront as StorefrontIcon,
  ShoppingBag as ShoppingBagIcon,
  LocalGroceryStore as GroceryIcon,
  Restaurant as RestaurantIcon,
  LocalCafe as CafeIcon,
  LocalBar as BarIcon,
  LocalPizza as PizzaIcon,
  Fastfood as FastfoodIcon,
  LocalDining as DiningIcon,
  Kitchen as KitchenIcon,
  Blender as BlenderIcon,
  Microwave as MicrowaveIcon,
  LocalLaundryService as LaundryIcon,
  CleaningServices as CleaningIcon,
  Handyman as HandymanIcon,
  Construction as ConstructionIcon,
  Engineering as EngineeringIcon,
  Architecture as ArchitectureIcon,
  DesignServices as DesignIcon,
  Draw as SketchIcon,
  Straighten as MeasureIcon,
  SquareFoot as SquareFootIcon,
  Carpenter as CarpenterIcon,
  Plumbing as PlumbingIcon,
  ElectricalServices as ElectricalIcon,
  Hvac as HvacIcon,
  Roofing as RoofingIcon,
  Foundation as FoundationIcon,
  Fence as FenceIcon,
  Yard as YardIcon,
  Grass as GrassIcon,
  Park as ParkIcon,
  Forest as ForestIcon,
  Nature as NatureIcon,
  NaturePeople as NaturePeopleIcon,
  Landscape as LandscapeIcon,
  Terrain as TerrainIcon,
  WbSunny as SunnyIcon,
  WbCloudy as CloudyIcon,
  Thunderstorm as ThunderstormIcon,
  AcUnit as SnowIcon,
  Opacity as RainIcon,
  Air as WindIcon,
  Waves as WavesIcon,
  Water as WaterIcon,
  WaterDrop as WaterDropIcon,
  Pool as PoolIcon,
  Spa as SpaIcon,
  FitnessCenter as GymIcon,
  SportsGymnastics as GymnasticsIcon,
  SportsBasketball as BasketballIcon,
  SportsSoccer as SoccerIcon,
  SportsFootball as FootballIcon,
  SportsBaseball as BaseballIcon,
  SportsTennis as TennisIcon,
  SportsGolf as GolfIcon,
  SportsVolleyball as VolleyballIcon,
  SportsHockey as HockeyIcon,
  SportsRugby as RugbyIcon,
  SportsCricket as CricketIcon,
  SportsKabaddi as MartialArtsIcon,
  SportsHandball as HandballIcon,
  Pool as SwimmingIcon,
  DirectionsRun as AthleticsIcon,
  Hiking as HikingIcon,
  Skateboarding as SkateboardIcon,
  Snowboarding as SnowboardIcon,
  Surfing as SurfingIcon,
  Kayaking as KayakingIcon,
  Rowing as RowingIcon,
  Sailing as SailingIcon,
  ScubaDiving as ScubaIcon,
  Paragliding as ParaglidingIcon,
  Kitesurfing as KitesurfIcon,
  NordicWalking as WalkingIcon,
  Sledding as SleddingIcon,
  DownhillSkiing as SkiingIcon,
  IceSkating as SkatingIcon,
  Casino as GamingIcon,
  SportsEsports as EsportsIcon,
  Gamepad as GamepadIcon,
  Mouse as MouseIcon,
  Keyboard as KeyboardIcon,
  Headphones as HeadphonesIcon,
  Speaker as SpeakerIcon,
  Tv as TvIcon,
  Monitor as MonitorIcon,
  DesktopWindows as DesktopIcon,
  Laptop as LaptopIcon,
  PhoneIphone as IphoneIcon,
  PhoneAndroid as AndroidPhoneIcon,
  Watch as WatchIcon,
  Memory as MemoryIcon,
  Storage as StorageIcon,
  SdCard as SdCardIcon,
  UsbRounded as UsbIcon,
  Router as RouterIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  SignalCellularAlt as SignalIcon,
  NetworkCheck as NetworkIcon,
  Bluetooth as BluetoothIcon,
  BluetoothConnected as BluetoothConnectedIcon,
  BluetoothDisabled as BluetoothDisabledIcon,
  Nfc as NfcIcon,
  LocationSearching as LocationSearchIcon,
  LocationDisabled as LocationDisabledIcon,
  SettingsInputAntenna as AntennaIcon,
  CellTower as TowerIcon,
  SatelliteAlt as SatelliteIcon,
  Radar as RadarIcon,
  Sensors as SensorsIcon,
  DeviceThermostat as ThermostatIcon,
  Thermostat as TempIcon,
  BatteryFull as BatteryFullIcon,
  BatteryCharging90 as BatteryChargingIcon,
  BatteryAlert as BatteryAlertIcon,
  PowerSettingsNew as PowerIcon,
  Power as PlugIcon,
  PowerOff as PowerOffIcon,
  FlashOn as FlashOnIcon,
  FlashOff as FlashOffIcon,
  Highlight as HighlightIcon,
  WbIncandescent as BulbIcon,
  Bedtime as SleepIcon,
  Alarm as AlarmIcon,
  AlarmOn as AlarmOnIcon,
  AlarmOff as AlarmOffIcon,
  Timer as TimerIcon,
  Timer10 as Timer10Icon,
  Timelapse as TimelapseIcon,
  AvTimer as AvTimerIcon,
  Snooze as SnoozeIcon,
  NotificationsActive as NotifActiveIcon,
  NotificationsOff as NotifOffIcon,
  NotificationsPaused as NotifPausedIcon,
  DoNotDisturb as DndIcon,
  DoNotDisturbOn as DndOnIcon,
  DoNotDisturbOff as DndOffIcon,
  ModeNight as NightIcon,
  LightMode as DayIcon,
  DarkMode as DarkIcon,
  Contrast as ContrastIcon,
  Brightness6 as BrightnessIcon,
  Exposure as ExposureIcon,
  FilterBAndW as BwFilterIcon,
  FilterVintage as VintageIcon,
  FilterDrama as DramaIcon,
  Gradient as GradientIcon,
  Blur as BlurIcon,
  BlurOn as BlurOnIcon,
  BlurOff as BlurOffIcon,
  Sharpen as SharpenIcon,
  Vignette as VignetteIcon,
  Grain as GrainIcon,
  Texture as TextureIcon,
  Style as StyleIcon,
  Pattern as PatternIcon,
  Face as FaceIcon,
  Face2 as Face2Icon,
  Face3 as Face3Icon,
  Face4 as Face4Icon,
  Face5 as Face5Icon,
  Face6 as Face6Icon,
  FaceRetouchingNatural as RetouchIcon,
  AutoFixHigh as AutoFixIcon,
  AutoFixNormal as AutoFixNormalIcon,
  AutoFixOff as AutoFixOffIcon,
  Healing as HealingIcon,
  ContentCut as CutIcon,
  ContentPaste as PasteIcon,
  ContentPasteGo as PasteGoIcon,
  ContentPasteSearch as PasteSearchIcon,
  ContentPasteOff as PasteOffIcon,
  SelectAll as SelectIcon,
  Deselect as DeselectAllIcon,
  CopyAll as CopyAllIcon,
  DragIndicator as DragIcon,
  DragHandle as DragHandleIcon,
  OpenWith as MoveIcon,
  PanTool as HandIcon,
  TouchApp as TouchIcon,
  Pinch as PinchIcon,
  Swipe as SwipeIcon,
  Gesture as GestureIcon,
  Fingerprint as FingerprintIcon,
  QrCode as QrCodeIcon,
  QrCode2 as QrCode2Icon,
  QrCodeScanner as QrScannerIcon,
  CropFree as ScannerIcon,
  DocumentScanner as DocScannerIcon,
  PhotoCamera as CameraIcon,
  CameraAlt as CamAltIcon,
  CameraFront as CamFrontIcon,
  CameraRear as CamRearIcon,
  SwitchCamera as SwitchCamIcon,
  FlipCameraAndroid as FlipCamIcon,
  FlipCameraIos as FlipCamIosIcon,
  CameraEnhance as CamEnhanceIcon,
  CameraRoll as CamRollIcon,
  PhotoLibrary as PhotoLibIcon,
  Photo as PhotoIcon,
  PhotoAlbum as AlbumIcon,
  PhotoFilter as PhotoFilterIcon,
  PhotoSizeSelectActual as PhotoActualIcon,
  PhotoSizeSelectLarge as PhotoLargeIcon,
  PhotoSizeSelectSmall as PhotoSmallIcon,
  Panorama as PanoramaIcon,
  PanoramaFishEye as FishEyeIcon,
  PanoramaHorizontal as PanoHorizIcon,
  PanoramaVertical as PanoVertIcon,
  PanoramaWideAngle as WideAngleIcon,
  Slideshow as SlideshowIcon,
  BurstMode as BurstIcon,
  Timer3 as Timer3Icon,
  HdrOn as HdrIcon,
  HdrOff as HdrOffIcon,
  HdrPlus as HdrPlusIcon,
  HdrAuto as HdrAutoIcon,
  WbAuto as WbAutoIcon,
  WbTwilight as TwilightIcon,
  WbShade as ShadeIcon,
} from '@mui/icons-material';

// React Icons (for additional icons)
export {
  FaGraduationCap,
  FaChalkboardTeacher,
  FaUserGraduate,
  FaBook,
  FaBookOpen,
  FaBookReader,
  FaPencilAlt,
  FaRegEdit,
  FaClipboardList,
  FaClipboardCheck,
  FaTasks,
  FaAward,
  FaMedal,
  FaTrophy,
  FaCrown,
  FaStar,
  FaStarHalfAlt,
  FaRegStar,
  FaHeart,
  FaRegHeart,
  FaThumbsUp,
  FaRegThumbsUp,
  FaThumbsDown,
  FaRegThumbsDown,
  FaComments,
  FaRegComments,
  FaComment,
  FaRegComment,
  FaEnvelope,
  FaRegEnvelope,
  FaBell,
  FaRegBell,
  FaBellSlash,
  FaRegBellSlash,
  FaCog,
  FaCogs,
  FaWrench,
  FaTools,
  FaUser,
  FaUserPlus,
  FaUserMinus,
  FaUsers,
  FaUserFriends,
  FaUsersCog,
  FaSignInAlt,
  FaSignOutAlt,
  FaLock,
  FaUnlock,
  FaKey,
  FaShieldAlt,
  FaEye,
  FaEyeSlash,
  FaSearch,
  FaSearchPlus,
  FaSearchMinus,
  FaFilter,
  FaSort,
  FaSortUp,
  FaSortDown,
  FaHome,
  FaBuilding,
  FaSchool,
  FaUniversity,
  FaGlobe,
  FaGlobeAmericas,
  FaGlobeEurope,
  FaGlobeAsia,
  FaGlobeAfrica,
  FaMapMarkerAlt,
  FaMapMarked,
  FaMap,
  FaCompass,
  FaPhone,
  FaPhoneAlt,
  FaMobileAlt,
  FaTabletAlt,
  FaDesktop,
  FaLaptop,
  FaTv,
  FaWifi,
  FaBluetooth,
  FaUsb,
  FaSdCard,
  FaServer,
  FaDatabase,
  FaCloud,
  FaCloudUploadAlt,
  FaCloudDownloadAlt,
  FaFolder,
  FaFolderOpen,
  FaFolderPlus,
  FaFolderMinus,
  FaFile,
  FaFileAlt,
  FaFilePdf,
  FaFileWord,
  FaFileExcel,
  FaFilePowerpoint,
  FaFileImage,
  FaFileVideo,
  FaFileAudio,
  FaFileArchive,
  FaFileCode,
  FaFileCsv,
  FaDownload,
  FaUpload,
  FaShare,
  FaShareAlt,
  FaLink,
  FaUnlink,
  FaExternalLinkAlt,
  FaPaperclip,
  FaPrint,
  FaSave,
  FaCopy,
  FaPaste,
  FaCut,
  FaTrash,
  FaTrashAlt,
  FaEdit,
  FaPen,
  FaPenFancy,
  FaHighlighter,
  FaEraser,
  FaPlus,
  FaMinus,
  FaTimes,
  FaCheck,
  FaCheckDouble,
  FaCheckCircle,
  FaTimesCircle,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaInfoCircle,
  FaQuestionCircle,
  FaArrowUp,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowAltCircleUp,
  FaArrowAltCircleDown,
  FaArrowAltCircleLeft,
  FaArrowAltCircleRight,
  FaChevronUp,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaAngleUp,
  FaAngleDown,
  FaAngleLeft,
  FaAngleRight,
  FaAngleDoubleUp,
  FaAngleDoubleDown,
  FaAngleDoubleLeft,
  FaAngleDoubleRight,
  FaPlay,
  FaPause,
  FaStop,
  FaForward,
  FaBackward,
  FaFastForward,
  FaFastBackward,
  FaStepForward,
  FaStepBackward,
  FaRedo,
  FaUndo,
  FaSyncAlt,
  FaExpand,
  FaExpandAlt,
  FaCompress,
  FaCompressAlt,
  FaVolumeUp,
  FaVolumeDown,
  FaVolumeMute,
  FaVolumeOff,
  FaMicrophone,
  FaMicrophoneAlt,
  FaMicrophoneSlash,
  FaVideo,
  FaVideoSlash,
  FaCamera,
  FaImage,
  FaImages,
  FaFilm,
  FaMusic,
  FaHeadphones,
  FaBroadcastTower,
  FaPodcast,
  FaRss,
  FaCalendar,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCalendarPlus,
  FaCalendarMinus,
  FaCalendarTimes,
  FaClock,
  FaRegClock,
  FaHistory,
  FaHourglass,
  FaHourglassStart,
  FaHourglassHalf,
  FaHourglassEnd,
  FaStopwatch,
  FaAlarmClock,
  FaSun,
  FaMoon,
  FaCloudSun,
  FaCloudMoon,
  FaRainbow,
  FaUmbrella,
  FaSnowflake,
  FaWind,
  FaTemperatureHigh,
  FaTemperatureLow,
  FaThermometerHalf,
  FaMoneyBill,
  FaMoneyBillAlt,
  FaMoneyBillWave,
  FaMoneyCheck,
  FaMoneyCheckAlt,
  FaCreditCard,
  FaWallet,
  FaCoins,
  FaPiggyBank,
  FaChartLine,
  FaChartBar,
  FaChartPie,
  FaChartArea,
  FaPercentage,
  FaCalculator,
  FaReceipt,
  FaFileInvoice,
  FaFileInvoiceDollar,
  FaShoppingCart,
  FaShoppingBag,
  FaShoppingBasket,
  FaStore,
  FaStoreAlt,
  FaBox,
  FaBoxOpen,
  FaBoxes,
  FaGift,
  FaTruck,
  FaTruckMoving,
  FaShippingFast,
  FaBarcode,
  FaQrcode,
  FaTag,
  FaTags,
  FaPercent,
  FaDollarSign,
  FaEuroSign,
  FaPoundSign,
  FaYenSign,
  FaRupeeSign,
  FaBitcoin,
  FaEthereum,
  FaFacebook,
  FaFacebookF,
  FaFacebookSquare,
  FaTwitter,
  FaTwitterSquare,
  FaInstagram,
  FaInstagramSquare,
  FaLinkedin,
  FaLinkedinIn,
  FaYoutube,
  FaYoutubeSquare,
  FaTiktok,
  FaSnapchat,
  FaSnapchatGhost,
  FaSnapchatSquare,
  FaPinterest,
  FaPinterestP,
  FaPinterestSquare,
  FaReddit,
  FaRedditAlien,
  FaRedditSquare,
  FaTumblr,
  FaTumblrSquare,
  FaWhatsapp,
  FaWhatsappSquare,
  FaTelegram,
  FaTelegramPlane,
  FaDiscord,
  FaSlack,
  FaSlackHash,
  FaSkype,
  FaViber,
  FaLine,
  FaWeixin,
  FaWeibo,
  FaQq,
  FaVk,
  FaMedium,
  FaMediumM,
  FaDribbble,
  FaDribbbleSquare,
  FaBehance,
  FaBehanceSquare,
  FaDeviantart,
  FaFlickr,
  FaVimeo,
  FaVimeoV,
  FaVimeoSquare,
  FaDailymotion,
  FaTwitch,
  FaSpotify,
  FaSoundcloud,
  FaApple,
  FaAndroid,
  FaWindows,
  FaLinux,
  FaUbuntu,
  FaChrome,
  FaFirefox,
  FaSafari,
  FaEdge,
  FaOpera,
  FaInternetExplorer,
  FaGithub,
  FaGithubSquare,
  FaGitlab,
  FaBitbucket,
  FaGit,
  FaGitAlt,
  FaCodepen,
  FaJsfiddle,
  FaStackOverflow,
  FaHackerrank,
  FaDev,
  FaNpm,
  FaYarn,
  FaNode,
  FaNodeJs,
  FaReact,
  FaVuejs,
  FaAngular,
  FaHtml5,
  FaCss3,
  FaCss3Alt,
  FaSass,
  FaLess,
  FaBootstrap,
  FaJs,
  FaJsSquare,
  FaPhp,
  FaPython,
  FaJava,
  FaSwift,
  FaRust,
  FaDocker,
  FaAws,
  FaMicrosoft,
  FaGoogle,
  FaGoogleDrive,
  FaDropbox,
  FaWordpress,
  FaWordpressSimple,
  FaBlogger,
  FaBloggerB,
  FaJoomla,
  FaDrupal,
  FaMagento,
  FaShopify,
  FaPaypal,
  FaStripe,
  FaCcVisa,
  FaCcMastercard,
  FaCcAmex,
  FaCcDiscover,
  FaCcDinersClub,
  FaCcJcb,
  FaCcPaypal,
  FaCcStripe,
  FaCcApplePay,
  FaAmazon,
  FaAmazonPay,
  FaGooglePay,
  FaGooglePlay,
  FaAppStore,
  FaAppStoreIos,
} from 'react-icons/fa';

// Heroicons (optional, via react-icons)
export {
  HiAcademicCap,
  HiArrowCircleDown,
  HiArrowCircleLeft,
  HiArrowCircleRight,
  HiArrowCircleUp,
  HiArrowDown,
  HiArrowLeft,
  HiArrowNarrowDown,
  HiArrowNarrowLeft,
  HiArrowNarrowRight,
  HiArrowNarrowUp,
  HiArrowRight,
  HiArrowSmDown,
  HiArrowSmLeft,
  HiArrowSmRight,
  HiArrowSmUp,
  HiArrowUp,
  HiAtSymbol,
  HiBackspace,
  HiBadgeCheck,
  HiBan,
  HiBeaker,
  HiBell,
  HiBookmark,
  HiBookmarkAlt,
  HiBookOpen,
  HiBriefcase,
  HiCalculator,
  HiCalendar,
  HiCamera,
  HiCash,
  HiChartBar,
  HiChartPie,
  HiChartSquareBar,
  HiChat,
  HiChatAlt,
  HiChatAlt2,
  HiCheck,
  HiCheckCircle,
  HiChevronDoubleDown,
  HiChevronDoubleLeft,
  HiChevronDoubleRight,
  HiChevronDoubleUp,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiChip,
  HiClipboard,
  HiClipboardCheck,
  HiClipboardCopy,
  HiClipboardList,
  HiClock,
  HiCloud,
  HiCloudDownload,
  HiCloudUpload,
  HiCode,
  HiCog,
  HiCollection,
  HiColorSwatch,
  HiCreditCard,
  HiCube,
  HiCubeTransparent,
  HiCurrencyBangladeshi,
  HiCurrencyDollar,
  HiCurrencyEuro,
  HiCurrencyPound,
  HiCurrencyRupee,
  HiCurrencyYen,
  HiCursorClick,
  HiDatabase,
  HiDesktopComputer,
  HiDeviceMobile,
  HiDeviceTablet,
  HiDocument,
  HiDocumentAdd,
  HiDocumentDownload,
  HiDocumentDuplicate,
  HiDocumentRemove,
  HiDocumentReport,
  HiDocumentSearch,
  HiDocumentText,
  HiDotsCircleHorizontal,
  HiDotsHorizontal,
  HiDotsVertical,
  HiDownload,
  HiDuplicate,
  HiEmojiHappy,
  HiEmojiSad,
  HiExclamation,
  HiExclamationCircle,
  HiExternalLink,
  HiEye,
  HiEyeOff,
  HiFastForward,
  HiFilm,
  HiFilter,
  HiFingerPrint,
  HiFire,
  HiFlag,
  HiFolder,
  HiFolderAdd,
  HiFolderDownload,
  HiFolderOpen,
  HiFolderRemove,
  HiGift,
  HiGlobe,
  HiGlobeAlt,
  HiHand,
  HiHashtag,
  HiHeart,
  HiHome,
  HiIdentification,
  HiInbox,
  HiInboxIn,
  HiInformationCircle,
  HiKey,
  HiLibrary,
  HiLightBulb,
  HiLightningBolt,
  HiLink,
  HiLocationMarker,
  HiLockClosed,
  HiLockOpen,
  HiLogin,
  HiLogout,
  HiMail,
  HiMailOpen,
  HiMap,
  HiMenu,
  HiMenuAlt1,
  HiMenuAlt2,
  HiMenuAlt3,
  HiMenuAlt4,
  HiMicrophone,
  HiMinus,
  HiMinusCircle,
  HiMinusSm,
  HiMoon,
  HiMusicNote,
  HiNewspaper,
  HiOfficeBuilding,
  HiPaperAirplane,
  HiPaperClip,
  HiPause,
  HiPencil,
  HiPencilAlt,
  HiPhone,
  HiPhoneIncoming,
  HiPhoneMissedCall,
  HiPhoneOutgoing,
  HiPhotograph,
  HiPlay,
  HiPlus,
  HiPlusCircle,
  HiPlusSm,
  HiPresentationChartBar,
  HiPresentationChartLine,
  HiPrinter,
  HiPuzzle,
  HiQrcode,
  HiQuestionMarkCircle,
  HiReceiptRefund,
  HiReceiptTax,
  HiRefresh,
  HiReply,
  HiRewind,
  HiRss,
  HiSave,
  HiSaveAs,
  HiScale,
  HiScissors,
  HiSearch,
  HiSearchCircle,
  HiSelector,
  HiServer,
  HiShare,
  HiShieldCheck,
  HiShieldExclamation,
  HiShoppingBag,
  HiShoppingCart,
  HiSortAscending,
  HiSortDescending,
  HiSparkles,
  HiSpeakerphone,
  HiStar,
  HiStatusOffline,
  HiStatusOnline,
  HiStop,
  HiSun,
  HiSupport,
  HiSwitchHorizontal,
  HiSwitchVertical,
  HiTable,
  HiTag,
  HiTemplate,
  HiTerminal,
  HiThumbDown,
  HiThumbUp,
  HiTicket,
  HiTranslate,
  HiTrash,
  HiTrendingDown,
  HiTrendingUp,
  HiTruck,
  HiUpload,
  HiUser,
  HiUserAdd,
  HiUserCircle,
  HiUserGroup,
  HiUserRemove,
  HiUsers,
  HiVariable,
  HiVideoCamera,
  HiViewBoards,
  HiViewGrid,
  HiViewGridAdd,
  HiViewList,
  HiVolumeOff,
  HiVolumeUp,
  HiWifi,
  HiX,
  HiXCircle,
  HiZoomIn,
  HiZoomOut,
} from 'react-icons/hi';